apiVersion: v1
kind: pod
metadata:
  name: nginx
  Namespace: robo-vijay
spec:
  containers:
    - name: nginx
      image: nginx:latest
      port:
      - containerPort:80
    - name: jenkins
      image: jenkins/jenkins
      port:
      - containerPort:8080
    