apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: robo-vijay
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
    - name: jenkins
      image: jenkins/jenkins
      ports:
      - containerPort: 8080